### ISSUE TITLE
Unable to Install or Run

### ISSUE THREAD

**Issue by AllenSeitz** [olji/infinitas_statfetcher#2]
First let me say thank you for making this program! I had my own version of this program for Infinitas 1st Style that served my needs well. But I had difficulty updating for Infinitas 2020 and I haven't updated yet. (What was a static array of score data on the stack in Infinitas 1 turned into a dynamic data structure on the heap in 2020. So I can't just grab a static range anymore like I can for the rival data or the songlist.)

I don't know how you solved that problem? Or if you only dump the live/current score and can't handle existing scores like I was trying to? But either way I endorse this program. I personally prefer ReadProcessMemory() over dll hooking and I think you're doing it right. Also you've got more features and a method to update the offsets automatically from an authority. Love it!

ACTUAL ISSUE:
Anyways infinitas_statfetcher depends on the Dot Net Desktop Runtime and this isn't mentioned in the ReadMe. After installing the runtime I was told that basically 5.0.5 was too new and that 3.1.0 was needed. If you could maybe statically compile that dependency in there or include a link to the installer either would be helpful.

**Comment by olji** [comment]
Infinitas keeping track of historical scoring data in memory never occured to me actually, I just built it to dump the current score, its metadata, and whatever more I wanted to keep track of.

Seems like I didn't have .NET Native on my system so when I built it statically it was in the intermediate language and still needed the framework.
I could reproduce and subsequently fix the issue on a virtual machine with a fresh install, which is available as the latest release now.
 
On the topic of runtimes, I should probably migrate to .NET 5, I just picked the first console project template on the list when I started this project.

Thanks for reminding me of the readme actually, I haven't updated it in a while.

**Comment by AllenSeitz** [comment]
Thank you for the quick fix! I'd try it right now but the server is down. I'm going to share this program with my friends who play.

Just in case you're interested:
Dumping all scores should be easiest on the songwheel. Because at that time we know that the exscore, miss count, and lamp for every song and chart has to be readily available. (Even if the player has scores on songs they can't see.) I took this data, made an arcade-style csv, and used that for what you normally use that for.

The problem I ran into with the 120hz update is that the data structure now looks something like: {data for 21 songs, 64 bytes of padding, data for 40 songs, skip 196 bytes, data for 12 songs, skip 512 huge bytes} etc. And of course these arbitrary numbers changed for each run of the program. So probably this stuff is being stored in something like a std::vector and I'm going to have to find the pointers. I don't know if you'll succeed or invent a different and easier way? But there you go.

**Comment by olji** [comment]
Interesting, I might look into that for fun some time.

**Comment by olji** [comment]
I figured it out now, it is storing everything in a hashmap with linked lists. The start and end of that hashmap is present in static memory so it's fetchable.

Latest release saves and outputs what's found in that structure into the file tracker.tsv

**Comment by AllenSeitz** [comment]
You're the best! Congrats on all the new features btw.
